export const SKILLS = [
  "JavaScript (ES6+)",
  "TypeScript",
  "React.js",
  "Next.js",
  "C#",
  "Kotlin",
  "DSA",
  "Swift",
  "Node.js",
  "Express.js",
  "MERN Stack Development",
  "Django",
  "Java Spring Boot",
  "C || C++",
  "Computer Networking",
  "OS",
  "Python flask",
  "RESTful API Development",
  "MySQL || Oracle",
  "PostgreSQL",
  "Deep learning",
  "Kubernets",
  "Flutter",
  "Cyber Secruity",
  "Unity || engine",
  "Game Development",
  "Artificial Intelligence (AI)",
  "Machine Learning",
  "Data Science",
  "Git & GitHub",
  "Docker",
  "CI/CD Pipelines",
  "Linux",
  "Cloud Computing (AWS Basics)",
];
